### ISSUE TITLE
我运行test.py就这样了，要求的环境我也安装了呀这种情况是如何解决的啊

### ISSUE THREAD

**Issue by clq12** [sb-child/lsp#1]
Traceback (most recent call last):
  File "L:\✳总下载\星愿\lsp-main\lsp-main\test.py", line 3, in <module>
    import decryptLink
  File "L:\✳总下载\星愿\lsp-main\lsp-main\decryptLink.py", line 1, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

进程已结束，退出代码为 1

**Comment by clq12** [comment]
![image](https://user-images.githubusercontent.com/45648440/113532577-42ce9a00-95fe-11eb-8fdd-bf25c77294aa.png)
还有这种情况

**Comment by sb-child** [comment]
在cmd运行命令 以安装缺少的第三方库
```pip install pycryptodome```

另外, 对方的网站最近似乎出现了些问题, 导致下载失败.

若要下载视频, 还需要额外安装`ffmpeg`
