### ISSUE TITLE
我感觉可以加点分类

### ISSUE THREAD

**Issue by clq12** [sb-child/lsp#3]
我感觉可以加点分类，这样子就能更为有效的去。。。。。

**Comment by sb-child** [comment]
考虑过加分类...
又考虑到多次下载的重复问题..
---

那我可以加上分类.

**Comment by clq12** [comment]
下载重复其实还好吧，现在有很多查重的

**Comment by sb-child** [comment]
搞定(目前只支持yysp)
535dc1d4532f6f6d9f55a97a2af98b919d5f7645

**Comment by sb-child** [comment]
已经适配了`miya`

1104ac1a36bd8df7df5c7c4c8b2dfb73f23878ee
90e0bbb3ec682dfdfcea41a87036707e57354792

**Comment by sb-child** [comment]
关于分类的其他问题, 请新建issue
