### ISSUE TITLE
这个用test2可以采集但是用modrun不可以

### ISSUE THREAD

**Issue by clq12** [sb-child/lsp#5]
这个用test2可以采集但是用modrun不可以，这样是什么情况啊
![image](https://user-images.githubusercontent.com/45648440/117115427-b01d4880-adbf-11eb-9546-30be290b4f19.png)
![image](https://user-images.githubusercontent.com/45648440/117115522-cc20ea00-adbf-11eb-827d-9ccfc13750c9.png)

**Comment by sb-child** [comment]
hashlib安装失败?

**Comment by sb-child** [comment]
你用 `git bash` 试试?

**Comment by sb-child** [comment]
鉴于hashlib已经很久没有人维护..考虑改用其他库实现

**Comment by clq12** [comment]
直接用cmd是可以的，但是经常采集一两个就会卡住

**Comment by sb-child** [comment]
> 直接用cmd是可以的，但是经常采集一两个就会卡住

最近yysp的服务器有些慢..建议用miya

**Comment by sb-child** [comment]
> 直接用cmd是可以的，但是经常采集一两个就会卡住

部分视频需要额外使用key解密..我将适配这个

**Comment by sb-child** [comment]
> > 直接用cmd是可以的，但是经常采集一两个就会卡住
> 
> 部分视频需要额外使用key解密..我将适配这个

搞定 e090f0606dbe46880d146fb604830b67e6358fce
