### ISSUE TITLE
现在用test怎么都会这样了啊

### ISSUE THREAD

**Issue by clq12** [sb-child/lsp#8]
![image](https://user-images.githubusercontent.com/45648440/121799414-91339100-cc5e-11eb-8f44-c3ae093939eb.png)

**Comment by sb-child** [comment]
首先, `test.py` 已被弃用, 现在建议使用`modRun.py`.

另外, 参见[此处](https://github.com/sb-child/lsp#%E5%BF%AB%E9%80%9F%E5%85%A5%E6%89%8B)安装`jsdec-tiny`插件, 才能使用`miya`模块.
